USE Octocat;

/* SAMPLE DATA: Giving a user to log in with */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE User; SET FOREIGN_KEY_CHECKS = 1;
insert into User
values (NULL, 'brentrockwell', 'testing123', 'brent', '', 'rockwell', CAST('1984-09-11' AS DATE), true, true);

select *
from User;

/* SAMPLE DATA: Giving a user 2 addresses */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE Phone; SET FOREIGN_KEY_CHECKS = 1;
insert into Phone
values (NULL,
        (select user_id from User where username= 'brentrockwell'),
        '408-204-0929',
        (select PHONETYPE_ID from PhoneType where phonetype = 'Mobile Phone')),
       (NULL,
        (select user_id from User where username= 'brentrockwell'),
        '408-555-1212',
        (select PHONETYPE_ID from PhoneType where phonetype = 'Work Phone'));

select *
from Phone;

/* SAMPLE DATA: Giving a user 2 addresses */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE Email; SET FOREIGN_KEY_CHECKS = 1;
insert into Email
values (NULL, NULL, 'fubar@aol.com', true),
       (NULL, (select user_id from User where username= 'brentrockwell'), 'brentcrockwell@gmail.com', true);

select *
from Email;

/* SAMPLE DATA: Giving a user 2 addresses */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE Address; SET FOREIGN_KEY_CHECKS = 1;
insert into Address
values (NULL,
        (select user_id from User where username= 'brentrockwell'),
        true,
        '1234 fake st',
        NULL,
        'faketown',
        (select state_id from State where abbreviation= 'CA'),
        '00000',
        false),
       (NULL,
        (select user_id from User where username= 'brentrockwell'),
        false,
        '2345 imaginary rd',
        NULL,
        'fancyplace',
        (select state_id from State where abbreviation= 'HI'),
        '10101',
        false);

select *
from Address;

/* SAMPLE DATA: Showing the user had an old and new credit card */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE Payment; SET FOREIGN_KEY_CHECKS = 1;
insert into Payment
values (NULL,
        (select user_id from User where username= 'brentrockwell'),
        false,
        (select cardtype_id from CardType where cardtype='Discover'),
        'Brent C Rockwell',
        '6000-0000-0000-0000',
        CAST('2022-10-01' as date),
        true),
       (NULL,
        (select user_id from User where username= 'brentrockwell'),
        true,
        (select cardtype_id from CardType where cardtype='visa'),
        'Brent C Rockwell',
        '4000-0000-0000-0000',
        CAST('2024-06-01' as date),
        false);

select *
from Payment;

/* SAMPLE DATA: Creating products to show on website */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE Product; SET FOREIGN_KEY_CHECKS = 1;
insert into Product
values -- 3D MODELS --
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Rocksteady',
        '3D model of Rocksteady from Teenage Mutant Ninja Turtles',
        14.99,
        '../media/img/rhino.gif',
        3503,
        2000,
        2200,
        true,
        false,
        NULL,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'SpongeBob',
        '3D model of SpongeBob SquarePants',
        1.99,
        '../media/img/spongebob.gif',
        470,
        200,
        215,
        true,
        true,
        NULL,
        NULL),
        (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Link',
        '3D model of Link from Zelda',
        4.99,
        '../media/img/link.gif',
        4203,
        2000,
        2200,
        false,
        false,
        NULL,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Ray',
        '3D model of Ray from no one knows where',
        2.99,
        '../media/img/ray.gif',
        1253,
        1500,
        1536,
        false,
        false,
        NULL,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Aang',
        '3D model of a Aang from Avatar: the Last Airbender',
        3.99,
        '../media/img/avatar.gif',
        3700,
        2500,
        2536,
        true,
        true,
        NULL,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Fone Bone',
        '3D model of a Fone Bone from Bone comics',
        0.89,
        '../media/img/bone.gif',
        1953,
        2300,
        2320,
        true,
        false,
        NULL,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Child',
        'Basic 3D model of a child',
        1.49,
        '../media/img/avatar.gif',
        800,
        1700,
        1735,
        false,
        false,
        NULL,
        NULL),
        (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Boulder',
        '3D model of an big rock',
        0.49,
        '../media/img/firstmodel.gif',
        800,
        9800,
        9853,
        false,
        false,
        NULL,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Lightsaber',
        '3D model of a Lightsaber from Star Wars',
        3.49,
        '../media/img/lightsaber.gif',
        600,
        800,
        896,
        true,
        true,
        NULL,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='3D Models'),
        'Rock',
        '3D model of a a rock',
        0.99,
        '../media/img/rock.gif',
        30,
        100,
        142,
        false,
        false,
        NULL,
        NULL);
insert into Product
values -- AUDIO --
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Sword Swing',
        'Sound clip of a sword swinging through the air',
        0.25,
        '../media/img/Sound.jpg',
        32,
        NULL,
        NULL,
        NULL,
        NULL,
        2.5348,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Fall',
        'Sound clip of an object falling',
        0.29,
        '../media/img/Sound.jpg',
        43,
        NULL,
        NULL,
        NULL,
        NULL,
        3.5698,
        NULL),
        (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Gun Shot',
        'Sound clip of a gunshot',
        0.22,
        '../media/img/Sound.jpg',
        12,
        NULL,
        NULL,
        NULL,
        NULL,
        1.3654,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Leaves Crunch',
        'Sound clip of leaves being crunched',
        0.37,
        '../media/img/Sound.jpg',
        12,
        NULL,
        NULL,
        NULL,
        NULL,
        1.5963,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Death Cry',
        'Sound clip of something dying',
        3.99,
        '../media/img/Sound.jpg',
        45,
        NULL,
        NULL,
        NULL,
        NULL,
        4.5263,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Bones',
        'Sound clip of bones clacking',
        0.89,
        '../media/img/Sound.jpg',
        43,
        NULL,
        NULL,
        NULL,
        NULL,
        3.1856,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Door close',
        'Sound clip of a door clacking shut',
        1.49,
        '../media/img/Sound.jpg',
        12,
        NULL,
        NULL,
        NULL,
        NULL,
        0.8964,
        NULL),
        (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Wind',
        'Sound clip of a wind blowing',
        0.49,
        '../media/img/Sound.jpg',
        67,
        NULL,
        NULL,
        NULL,
        NULL,
        5.1841,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Creaking',
        'Sound clip of boards creaking',
        3.49,
        '../media/img/Sound.jpg',
        42,
        NULL,
        NULL,
        NULL,
        NULL,
        3.5846,
        NULL),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Audio'),
        'Howl',
        'Sound clip of something howling in the distance',
        0.99,
        '../media/img/Sound.jpg',
        88,
        NULL,
        NULL,
        NULL,
        NULL,
        6.5381,
        NULL);
insert into Product
values -- SCRIPTS --
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'PlayerController',
        'A script that helps manage player movement and health',
        14.99,
        '../media/img/Script_Icon.png',
        123,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1756),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'GameController',
        'A script that helps manage game win conditions, time, weather, etc',
        14.99,
        '../media/img/Script_Icon.png',
        234,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        8562),
        (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'SpawnController',
        'A script that controls when, where, and what mobs spawn',
        4.99,
        '../media/img/Script_Icon.png',
        134,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        3512),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'InventorySystem',
        'A script to manage a players inventory',
        2.99,
        '../media/img/Script_Icon.png',
        254,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        3586),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'QuestSystem',
        'A script to help manage the creation and tracking of quests',
        3.99,
        '../media/img/Script_Icon.png',
        137,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1738),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'PlayerEquipment',
        'A script to help keep track of what items the player has equipped',
        0.89,
        '../media/img/Script_Icon.png',
        65,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        638),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'BossEncounter',
        'A script to keep track of bosses, fight stages, etc',
        1.49,
        '../media/img/Script_Icon.png',
        84,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        812),
        (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'SandboxSystem',
        'A script to help with sandbox games where you can build items',
        0.49,
        '../media/img/Script_Icon.png',
        472,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        12596),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'SkillTreeSystem',
        'A script for creating skill trees for RPGs',
        3.49,
        '../media/img/Script_Icon.png',
        135,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1538),
       (NULL,
        (select PRODUCTTYPE_ID from ProductType where producttype='Scripts'),
        'VoxelSystem',
        'A script for allowing a destructible world',
        0.99,
        '../media/img/Script_Icon.png',
        693,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        8628);

select *
from Product;

/* SAMPLE DATA: Showing the user has placed 2 orders */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE OrderHistory; SET FOREIGN_KEY_CHECKS = 1;
insert into OrderHistory
values (NULL,
        (select user_id from User where username= 'brentrockwell'),
        (select payment_id from Payment where user_id = (select user_id from User where username= 'brentrockwell') and removed=true),
        CAST('2018-12-24' as date),
        121.33),
       (NULL,
        (select user_id from User where username= 'brentrockwell'),
        (select payment_id from Payment where user_id = (select user_id from User where username= 'brentrockwell') and removed=false),
        CAST('2020-02-14' as date),
        215.46);

select *
from OrderHistory;

/* SAMPLE DATA: Showing the details of the 2 orders the customer placed */
SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE OrderDetails; SET FOREIGN_KEY_CHECKS = 1;
insert into OrderDetails
values (NULL, 1, 4, 1, 2.99),
       (NULL, 1, 11, 1, 0.25),
       (NULL, 1, 6, 1, 0.89),
       (NULL, 1, 21, 1, 14.99),
       (NULL, 1, 22, 1, 14.99),
       (NULL, 1, 18, 1, 0.49),
       (NULL, 1, 25, 1, 3.99),
       (NULL, 2, 5, 1, 3.99),
       (NULL, 2, 15, 1, 3.99),
       (NULL, 2, 16, 1, 0.89),
       (NULL, 2, 20, 1, 0.99),
       (NULL, 2, 23, 1, 4.99),
       (NULL, 2, 27, 1, 1.49);

select *
from OrderDetails;
